import { CHAT_MODEL, getAnthropic } from "@/lib/anthropic";
import type { ControlPlaybook } from "@/lib/playbook";

/**
 * Charlie-drafted compliance artifact generator. Given a CMMC L1 practice and
 * the org's onboarding context, returns a Markdown document the user can save
 * as evidence (after they fill in the bracketed placeholders). The output is
 * intentionally a DRAFT — it always includes a "[REVIEW BEFORE SUBMITTING]"
 * banner and bracketed `[FILL IN: ...]` placeholders for facts Charlie does
 * not have. We do not let the AI invent SAM UEIs, employee names, or system
 * inventories that were not supplied.
 *
 * Cost guard: ~1.5k output tokens × Sonnet 4.6. One call per generate click.
 */

const SYSTEM_PROMPT = `You are Charlie, a virtual compliance officer drafting CMMC Level 1 evidence documents for a small U.S. defense-tech company.

Your job: produce a complete, well-structured Markdown document that the user could review, fill in any [FILL IN: ...] placeholders, sign, and submit as evidence for the named CMMC practice. The document must:

- Open with a single H1 title naming the company and the practice (e.g. "# Authorized Users Roster — Acme Robotics, Inc.").
- Include a date line: "**Date:** [FILL IN: today's date]" if no date is supplied.
- Reference the relevant FAR / NIST citation in a footer line.
- Use the company's REAL information when supplied: legal name, scoped systems, NAICS codes, locations, employee counts. Never invent specifics.
- For everything you do not know, write "[FILL IN: <plain-English description of what to write>]". Never make up users, IPs, vendors, account names, or counts.
- Match the document type to the practice. For roster-style practices, produce a Markdown table (System | User | Role | Status | Date Added). For policy-style practices (acceptable use, screen lock, media handling), produce numbered policy clauses written in plain English. For procedure-style practices (visitor escort, media destruction), produce numbered steps + a sign-off table.
- End with: "**Prepared by:** [FILL IN: name and role]" then "**Signature:** ____________________  **Date:** ____________________"
- DO NOT include any pre-amble or post-amble outside the document. Output ONLY the Markdown document.

Tone: professional, plain-English, no marketing language, no emojis, no exclamation points.`;

export type GenerateArtifactInput = {
  practice: Omit<ControlPlaybook, "suggestedNarrative">;
  companyName: string;
  scopedSystems: string;
  naicsCodes: string[];
  entityType: string | null;
  /** Flattened business_profile facts already formatted by the caller. */
  profileFacts: string;
};

export async function generateArtifactDraft(
  input: GenerateArtifactInput,
): Promise<string> {
  const client = getAnthropic();

  // Pull the manual-provider template hint (if any) — that's the closest
  // thing the playbook has to a document spec for this practice.
  const manual = input.practice.providerGuidance.find(
    (p) => p.provider === "manual",
  );
  const templateHint = manual?.template
    ? `Template name: ${manual.template.label}\nTemplate purpose: ${manual.template.description}`
    : "No prebuilt template — choose the document type that best fits the passing-evidence checklist.";

  const userPrompt = `## Practice
ID: ${input.practice.id}
Title: ${input.practice.title}
FAR: ${input.practice.farReference}
NIST: ${input.practice.nistReference}
Plain English: ${input.practice.plainEnglish}

## What 'passing' evidence looks like
${input.practice.passingEvidence.map((e) => `- ${e}`).join("\n")}

## Common gotchas (avoid these in the draft)
${input.practice.commonGotchas.map((g) => `- ${g}`).join("\n")}

## Document spec
${templateHint}

## Company context
- Legal name: ${input.companyName}
- Entity type: ${input.entityType ?? "(not provided)"}
- NAICS codes: ${input.naicsCodes.length > 0 ? input.naicsCodes.join(", ") : "(none on file)"}
- Scoped systems: ${input.scopedSystems || "(not provided)"}

## Onboarding profile facts
${input.profileFacts || "(no profile data captured yet)"}

Now produce the Markdown document.`;

  const response = await client.messages.create({
    model: CHAT_MODEL,
    max_tokens: 2000,
    system: SYSTEM_PROMPT,
    messages: [{ role: "user", content: userPrompt }],
  });

  const text = response.content
    .filter((b) => b.type === "text")
    .map((b) => (b as { type: "text"; text: string }).text)
    .join("\n")
    .trim();

  if (!text) throw new Error("Charlie returned an empty draft");

  // Prepend the review banner so the user understands this is not yet ready
  // to attest against — they must fill placeholders and review.
  return `> **[REVIEW BEFORE SUBMITTING]** This draft was generated by Charlie from your onboarding profile and the CMMC L1 practice description. Fill in every \`[FILL IN: ...]\` placeholder, verify every fact, and have the appropriate person sign it before submitting as evidence.\n\n${text}\n`;
}

/**
 * Flatten a business_profile.data JSON blob into bullet lines for the prompt.
 * Same shape as the helper in bid-drafting.ts — kept separate to avoid a
 * cross-import that would couple the two modules.
 */
export function formatProfileFacts(data: Record<string, unknown>): string {
  if (!data || typeof data !== "object") return "";
  const lines: string[] = [];
  for (const [key, value] of Object.entries(data)) {
    if (value == null) continue;
    const human = key.replace(/_/g, " ");
    if (typeof value === "string") {
      if (value.trim()) lines.push(`- ${human}: ${value.trim()}`);
    } else if (Array.isArray(value)) {
      const items = value.filter((v) => v != null && String(v).trim());
      if (items.length > 0) lines.push(`- ${human}: ${items.join(", ")}`);
    } else if (typeof value === "object") {
      lines.push(`- ${human}: ${JSON.stringify(value)}`);
    } else {
      lines.push(`- ${human}: ${String(value)}`);
    }
  }
  return lines.join("\n");
}
